name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Debug app folder
        run: ls -la app
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - name: Set Image Variables
        run: >
          echo "IMAGE_URI=us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID
          }}/app-repo/demo-app:${{ github.sha }}" >> $GITHUB_ENV
      - name: Build Image
        run: |
          IMAGE_URI=us-central1-docker.pkg.dev/${CLOUDSDK_CORE_PROJECT}/app-repo/demo-app:${{ github.sha }}
          docker build -t $IMAGE_URI ./app
      - name: Push Image
        run: |
          IMAGE_URI=us-central1-docker.pkg.dev/${CLOUDSDK_CORE_PROJECT}/app-repo/demo-app:${{ github.sha }}
          docker push $IMAGE_URI
      - name: Deploy Cloud Run
        run: |
          IMAGE_URI=us-central1-docker.pkg.dev/${CLOUDSDK_CORE_PROJECT}/app-repo/demo-app:${{ github.sha }}
          gcloud run deploy demo-app \
           --image $IMAGE_URI \
           --region us-central1 \
           --platform managed \
           --allow-unauthenticated

